---
title: "HW1"
author: "YI JUNG CHEN"
date: "2019/1/21"
output: word_document
---
#2. (2 pts) In the second variant of rescale01(), infinite values are left unchanged. Rewrite rescale01() so that -Inf is mapped to 0, and Inf is mapped to 1.  Add error checking to return the message “Error: input must be numeric” if the input is not all numeric.
```{r}
###19.2.1 #2

x<-c(Inf,-Inf,4,5,NA)
rescale01 <- function(x) {
  if(is.numeric(x)==FALSE){
    print("Error: input must be numeric")
  } else
  (is.numeric(x)==TRUE)
  rng <- range(x, na.rm = TRUE, finite=TRUE)
  x<-(x - rng[1]) / (rng[2] - rng[1])
  x[x==Inf]<-1
  x[x==-Inf]<-0
  x
  }

rescale01(x)

#x[x==Inf]<-1, and  x[x==-Inf]<-0 is taught by one of our classmates
```

```{r}
###19.2.1 #5

x<-c(1,2,NA,3,5)
y<-c(2,NA,NA,4,8)

both_na<-function(x,y){
  x_na<-is.na(x)
  y_na<-is.na(y)
  sum(x_na&y_na)
}

both_na(x,y)
```

```{r}
###19.3.1 #1

recognize_prefix <- function(string, prefix) {
  substr(string, 1, nchar(prefix)) == prefix
}
recognize_prefix("abc","ab")
#recognize if the element of string will equal to its prefix 

reduce_last_one <- function(x) {
  if (length(x) <= 1) return(NULL)
  x[-length(x)]
}
reduce_last_one(c("apple",1,3))
#this function will reduce a vector of x, for example x<-c(2,3,5), the result will be 2,3

length_x_equal_length_y <- function(x, y) {
  rep(y, length.out=length(x))
}
length(c(1,3,10))
length_x_equal_length_y(c(1,3,10),c(1,4,3,3,3))
#this function will make the length of y equal to the length of x
```

```{r}
###19.4.4 #2
### reference:(https://github.com/siskavera/r4ds_exercises/blob/master/functions.R)
#got hour() function from GitHub, from this website, I know how to use hour() can bring up hour from now() function

library(lubridate)
now <- now()
greeting<-function(now){
  hour.now <- hour(now)
  if (hour.now < 12) {
    print("good morning")} else if 
  (hour.now < 18) {
    print("good afternoon")} else {
    print("good night")
  }
}
greeting(now)


```

```{r}
###19.4.4 #3

fizzbuzz<-function(x){
  if(x%%3==0&x%%5==0){
    print("fizzbuzz")}else if
  (x%%3==0){
    print("fizz")} else if
  (x%%5==0){
    print("buzz")}else{
      print(x)}
}
fizzbuzz(4)

fizzbuzz<-function(x){
  if(x%%15==0){
    print("fizzbuzz")}else if
  (x%%3==0){
    print("fizz")} else if
  (x%%5==0){
    print("buzz")}else{
      print(x)}
}

```

```{r}
###19.4.4 #4
#reference:(https://www.rdocumentation.org/packages/base/versions/3.5.2/topics/cut)
#from this website, I understand how to use cut(), break(), and labels() function
temp<-c(10,25,-3)
temp1<-cut(temp,breaks<-c(-Inf,0,10,20,30,Inf),labels<-c("freezing", "cold", "cool", "warm", "hot"),right=TRUE)

temp1

temp<-c(10,25,-3)
temp2<-cut(temp,breaks<-c(-Inf,0,10,20,30,Inf),labels<-c("freezing", "cold", "cool", "warm", "hot"),right=FALSE)

temp2
```




###additional

```{r}
x <- runif(5)
y1 <- ifelse(x < 0.5, 0, 1)
y1

aaa<-function(x){
for (i in 1:length(x)) {
  if (x[i] < 0.5) {
    y1[i] <- 0
  } else {
    y1[i] <- 1
  } 
  return(y1)
}
}
aaa(x)
```

```{r}
switch(1,
       "g" = "baba",
       "d" = "nana",
       stop("other"))
```

```{r}
x <- "c"
switch(x, 
       a = ,
       b = "ab",
       c = ,
       d = "cd"
)
```

